/* victim nmsg message module */

/*
 * Copyright (c) 2010 by Network Defence Intelligence, Inc. ("Defintel")
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND DEFINTEL DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS.  IN NO EVENT SHALL DEFINTEL BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT
 * OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#define MSGTYPE_SINK_ID		1
#define MSGTYPE_SINK_NAME	"sink"

/* Import. */

#include "sink.pb-c.c"

/* Data. */

struct nmsg_msgmod_field sink_fields[] = {
	{ .type = nmsg_msgmod_ft_uint32,	.name = "group"		},
	{ .type = nmsg_msgmod_ft_uint32,	.name = "rule"		},
	{ .type = nmsg_msgmod_ft_uint32,	.name = "sensor"	},
	{ .type = nmsg_msgmod_ft_uint16,	.name = "proto"		},
	{ .type = nmsg_msgmod_ft_ip,		.name = "srcip"		},
	{ .type = nmsg_msgmod_ft_uint16,	.name = "srcport"	},
	{ .type = nmsg_msgmod_ft_ip,		.name = "dstip"		},
	{ .type = nmsg_msgmod_ft_uint16,	.name = "dstport"	},
	{ .type = nmsg_msgmod_ft_string,	.name = "message"	},
	{ .type = nmsg_msgmod_ft_bytes,		.name = "payload"	},
	NMSG_MSGMOD_FIELD_END
};

/* Export. */

struct nmsg_msgmod_plugin nmsg_msgmod_ctx = {
	.msgver		= NMSG_MSGMOD_VERSION,
	.vendor		= NMSG_VENDOR_DEFINTEL,
	.msgtype	= { MSGTYPE_SINK_ID, MSGTYPE_SINK_NAME },

	.pbdescr	= &nmsg__defintel__sink__descriptor,
	.fields		= sink_fields
};

/*! \file sink.c
 * \brief Defintel "sink" message type.
 *
 * This message type is meant meant to carry information of a connection
 * to a sinkhole.
 *
 * <b>sink message fields.</b>

<table>

<tr>
<td><b> Name </b></td>
<td><b> Type </b></td>
<td><b> Required </b></td>
<td><b> Repeated </b></td>
<td><b> Description </b></td>
</tr>

<tr>
<td> group </td>
<td> uint32 </td>
<td> yes </td>
<td> no </td>
<td> Group ID - Used to indicate which malware/compromise group this message belongs to.
Note: Group ID numbers below 1000 are reserved for special purposes. An example
is a connection that was observed to a sinkhole/darknet that was not classified by an
existing sensor or rule. Reserved Group ID's are currently not well defined.
</td>
</tr>

<tr>
<td> rule </td>
<td> uint32 </td>
<td> yes </td>
<td> no </td>
<td> Rule ID - Used to indicate which rule in a group triggered this message </td>
</tr>

<tr>
<td> sensor </td>
<td> uint32 </td>
<td> no </td>
<td> no </td>
<td> Sensor ID - Used to indicate which sensor generated this message </td>
</tr>

<tr>
<td> proto </td>
<td> uint16 </td>
<td> no </td>
<td> no </td>
<td> IP protocol of the connection (6 = TCP, 17 = UDP, ICMP etc supported as well) </td>
</tr>

<tr>
<td> srcip </td>
<td> IP address </td>
<td> no </td>
<td> no </td>
<td> Source IP address (compromised address) </td>
</tr>

<tr>
<td> srcport </td>
<td> uint16 </td>
<td> no </td>
<td> no </td>
<td> Source port (compromised client port) </td>
</tr>

<tr>
<td> dstip </td>
<td> IP address </td>
<td> no </td>
<td> no </td>
<td> Destination IP address (sinkhole IP address) </td>
</tr>

<tr>
<td> dstport </td>
<td> uint16 </td>
<td> no </td>
<td> no </td>
<td> Destination port (port which compromised system is connecting to on the sinkhole) </td>
</tr>

<tr>
<td> message </td>
<td> string </td>
<td> no </td>
<td> no </td>
<td> Text string describing the compromise (generated by sensor) </td>
</tr>

<tr>
<td> payload </td>
<td> bytes </td>
<td> no </td>
<td> no </td>
<td> First 512 bytes of transport layer payload.
For TCP protocol, this is post segment reassembly
therefore contents may contain reassembled data from multiple packets
</td>
</tr>


</table>
 */
